### ISSUE TITLE
How to run watchers

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/activitywatch#108]
Stated a few times in the docs are watchers such as `aw-watcher-web` and `aw-watcher-spotify` etc. But it's never mentioned how these are run, or where to state them so `aw-qt` can pick them up and run them.

is `aw-watcher-web` already included within the server module (hence why there are urls along side titles)?

And how do we go about including new watchers that we can build?

**Comment by ErikBjare** [comment]
We've currently not implemented any way to add a watcher to be managed by `aw-qt`. 

`aw-watcher-spotify` needs minor tinkering to get running, but shouldn't be any problem to programmers. Install the dependencies with `pip` and then in the folder run `python3 aw_watcher_spotify` (which basically says "run the package located in folder aw_watcher_spotify"). Feel free to make a PR that adds this info to the README!

`aw-watcher-web` is a browser plugin, but it's in a similar state of WIP since it by default tries to connect to port 5666 (as opposed to 5600) for testing purposes. It's an easy fix though, just grep for the port, change it to 5600 and load it as an unpacked extension in your browser. There is no visualization available for it right now, but it does collect data.

**Comment by ErikBjare** [comment]
Oh, and I should probably add in case you missed:

You don't need to run watchers with aw-qt, it's just a convenience wrapper. All watchers are able to be run standalone, aw-qt just manages their processes.

**Comment by ErikBjare** [comment]
I started working on something to make running your own modules a lot easier: https://github.com/ActivityWatch/aw-qt/pull/27

**Comment by ErikBjare** [comment]
Closing this since the question is answered. Please reach out if you have any more questions or if you need help with something!

**Comment by yratof** [comment]
Awesome – fantastic progress :D Almost managed to get the spotify watcher up and running, but ran into issues with it not detecting user/secret etc

**Comment by ErikBjare** [comment]
I've stumbled upon that too, created an issue: https://github.com/ActivityWatch/aw-watcher-spotify/issues/4

Please make a comment there with any details you can provide.
