### ISSUE TITLE
Change name to ActivityWatcher

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#11]
ActivityWatch is confusing, ActivityWatcher is more clear.
It's now or never. 

Thoughts?

**Comment by ErikBjare** [comment]
Places we'd have to change:

 - [ ] Organization name
 - [ ] Name of activitywatch (this) repo (Might change to the PascalCase 'ActivityWatcher')
 - [ ] Website links and content
 - [ ] Documentation

Basically, grep all ActivityWatch projects after the term `ActivityWatch[^e]` and replace.

**Comment by johan-bjareholt** [comment]
I've gotten used to the name ActivityWatch so I'm probably not the perfect person to ask for an opinion, but i think it's better.

I have always thought about the name similar to "Neighbourhood watch", it's not a single person that watches but a group of people watching that then shares the gathered data between each other.

ActivityWatcher might also seem strange because it refers to it as one watcher while in reality there are multiple watchers.

**Comment by ErikBjare** [comment]
That's true, but from I've heard from more than one person that
ActivityWatch made them think of watches initially, which must be
confusing.

"ActivityWatchers" is an alternative, but has its own issues. There are
many watchers, but there is one software suite effectively making a single
watcher that watches a lot of different stuff. The reason we have multiple
watchers is just for the sake of modularity, not really a concern to an
end-user, most will probably never give it much thought.

I still think ActivityWatcher is better, primarily because it's easier for
someone new to understand what it does, even if it doesn't represent how
the software suite is actually designed.

**Comment by ErikBjare** [comment]
We're probably going to keep ActivityWatch. I really can't come up with enough good arguments to justify the change.

**Comment by ErikBjare** [comment]
Just last week someone thought ActivityWatch + the logo indicated some kind of connection to an actual watch, so now I'm bothered by this again...

But the switch is probably not worth it.
