### ISSUE TITLE
How to update / pull the latest version of everything

### ISSUE THREAD

**Issue by yratof** [ActivityWatch/activitywatch#118]
is there a nice command you're running to update everything? I'm seeing that there are submodules that are getting update & pulling AW doesn't account for this

**Comment by ErikBjare** [comment]
Could you try `git submodule update --recursive`? I think that should do it.

**Comment by johan-bjareholt** [comment]
`git submodule update --recursive` might not be enough if we have specified commit IDs in our submodules (which it seems like we do have? Atleast i can see it in aw-watcher-web). This is the complete and full answer to the question

https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules

We also have the scripts/pull-all.sh script, if you use it with the -a flag you will push all the latest submodules on master. The stackoverflow article should do the exact same thing more consicely though, so that's probably the best way to go.

**Comment by ErikBjare** [comment]
So, if you want the latest version of all submodules committed in the main repo, use: `git submodule update --recursive`

If you want the latest master branch on all submodules, use: `git submodule update --recursive --remote`

@johan-bjareholt Did you mean `push-all.sh` or `pull-all.sh`? Also, does this mean that we can remove the `pull-all.sh` script? (after we've written about `git submodule update --recursive --remote` in the docs) 

 - [ ] Add info about `git submodule update --recursive --remote` to dev docs

**Comment by johan-bjareholt** [comment]
That's correct :)

I've personally never used the push-all script and see little use of it, so I wouldn't mind if we removed that aswell.

**Comment by ErikBjare** [comment]
The push-all script is mostly useful when you want to ensure that you've pushed all the latest changes in the submodules before pushing the main repo (if not, CI will fail to clone the submodules). But `git submodule foreach git push` is equivalent as far as I can see. So yeah, I'll remove it.

 - [ ] Remove `push-all.sh` and `pull-all.sh`

**Comment by ErikBjare** [comment]
Alright, fixed in https://github.com/ActivityWatch/activitywatch/commit/72e3b9c2bc9c59b25696516b46a83fbf294abb28.

Please let us know if the instructions worked @yratof, they work for me :)

**Comment by ErikBjare** [comment]
Closing this, let us know if you have any further problems @yratof.
