### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by dufferzafar** [ActivityWatch/activitywatch#175]
The Qt app has a menu option to open the logs directory but those are the application logs, where is the collected data stored? SQLite DB? MongoDB?

**Comment by johan-bjareholt** [comment]
The default datastore is sqlite and is saved in ~/.local/share/activitywatch/aw-server on linux.

I thought we had documented that in the docs but apparently we havn't, should be added.

**Comment by dufferzafar** [comment]
@johan-bjareholt Should there be an option for this in the Qt menu? I don't think why someone would want easy access to the data directory, but yeah it should atleast be documented somewhere in the docs etc.

**Comment by johan-bjareholt** [comment]
> Should there be an option for this in the Qt menu?

Probably not, in most cases if you want to export the data you'd likely want to go to the WebUI and use the export button. 

However since our import functionality is not done yet (but should be easier with the export API endpoint recently made by @ErikBjare) the easiest way is currently to just copy the .db file from that folder. So it definitely could be useful and should be documented.

**Comment by ErikBjare** [comment]
I'm considering this question answered. Just let us know if any further questions arise!
