### ISSUE TITLE
Windows Defender flags aw-watcher-afk (v0.8.0b5) as a trojan

### ISSUE THREAD

**Issue by overdamped** [ActivityWatch/activitywatch#219]
Windows Defender flagged aw-watcher-afk.exe as a trojan in v0.8.0b5 for windows x86.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fTiggre!plock&threatid=2147723626

**Comment by ErikBjare** [comment]
It's really weird that it marks aw-watcher-afk of all things as a trojan. I used to think it was an issue with PyInstaller (but then it would mark all `aw-*.exe` executables as a trojan) and then I thought it was an issue with us bundling PyUserInput (which we no longer do on Windows, instead we rely on native APIs to get seconds since last input).

I have no idea what would make them flag `aw-watcher-afk`. At least I'd understand it if they marked `aw-watcher-window` as it collects sensitive information.

I'm tired of playing games with the anti virus vendors and will just ignore them as their unpredictability is not worth my time.

Duplicate (but for a newer version), so closing.

**Comment by ErikBjare** [comment]
Okay, so I just stumbled upon this myself when trying to run it in a VM. Annoying, I know, and after having gone through the confusion of "where the fuck did aw-watcher-afk.exe go?" I can appreciate how this is kind of a big deal.

Still not sure what to do about it. We could proactively submit releases for analysis but that would take me too much time to be worth it for every single release. Might consider it for stable releases though.
