### ISSUE TITLE
Deploy with Conda

### ISSUE THREAD

**Issue by matt-chan** [ActivityWatch/activitywatch#220]
The current method of installing activitywatch is a little bit unreliable. Distributing releases with all the shared objects (eg QT) relies on having certain versions of glibc on your system (RHEL's version is too old for example). The source build seems to rely a lot on pip and npm as well.

Have you considered deploying everything via conda? It gives you the equivalent of a virtualenv, but it includes the C/C++ compilers for your OS, plus matching libstdc++, glibc for your system. It removes much of the headache of distributing binary objects via pip. It also has many nodejs and python flavours available already, so it can already provide all the deps needed for activitywatch (reducing the reliance on pip/npm). Whatever isn't provided can still be installed via pip/npm, or can be published to a 3rd party conda channel. In our own projects, we make conda releases automatically via git tag in travis.yml and the setup is fairly simple.

**Comment by ErikBjare** [comment]
Sorry, but I really don't want to introduce conda as a build-time dependency, especially since I've never ever used it and wouldn't know if it was a good fit without putting in a lot of time and effort. I don't want to have to learn yet another thing when the current solution works (although not perfectly, I'll admit).

Closing.
