### ISSUE TITLE
Taking screenshots in the background

### ISSUE THREAD

**Issue by mahanmp** [ActivityWatch/activitywatch#226]
Is there any feature available for ActivityWatch to make screenshots in the background of the current screen of the user and upload it automatically on the aw-server?

**Comment by johan-bjareholt** [comment]
No there is not

And since ActivityWatch is about fetching metadata about your computer usage and do analysis on it to show your computer usage behaviours and that it's next to impossible to parse metadata (and inefficient) from a screenshot this is not something we will implement either.

**Comment by aftabnaveed** [comment]
Would it not be possible to grab the screenshot upload it to cloud such as Amazon S3 and then save the URL, is that not something which would work?

**Comment by ErikBjare** [comment]
Sure, that would work, or just store the screenshot locally in a designated folder for that matter. 

Feel free to implement a watcher that does just that, shoudn't be too much work (I'd recommend saving the filepath to the screenshot, along with a hash of it). :slightly_smiling_face:

**Comment by aftabnaveed** [comment]
Yep I am still trying to understand the the architecture, hopefully soon :)

**Comment by backofficeteam** [comment]
dealbreaker for me -this is really useful in mainctime

**Comment by aftabnaveed** [comment]
This is an opensource project you can always come up with one :-)

**Comment by OndroMih** [comment]
I'm also thinking about how to do this, as it's pretty useful do go over screenshots to remember what I was doing. I can imagine how to take screenshots, save them to disk and send a link to them into a bucket, but how they would be visualized in the Dashboard? Obviously, I can just go into the directory on the disk to see the screenshots, but it would be nice if the Dashboard showed them for me in the timeline or in an Activity visualization.

**Comment by ErikBjare** [comment]
@OndroMih Honestly, I think it would just make more sense to have automatic screenshots as a separate thing entirely. 

I'm hesitant to add this as a part of ActivityWatch directly (due to privacy concerns), and integrating a very special watcher, like the one you describe, with the web UI sounds messy.

But I'd still love to see people implement something like this (maybe there already is?) as a complement to ActivityWatch, it's just unlikely to get the "official" treatment :)

**Comment by lixaotec** [comment]
Would you provide some  hints to accomplish this in linux?

How would be the best way to take the screenshot? I could did into it.

**Comment by ErikBjare** [comment]
@lixaotec You can install something like [escrotum](https://github.com/Roger/escrotum) that allows you to take screenshots from the command line, then write a script that takes one every x min.

**Comment by huachuman** [comment]
ManicTime does this very well, giving the user the option to take a screenshot both every x seconds and on every application switch. It also lets the user choose whether to capture the whole screen or just the active window. It also allows you to choose the quality and filetype in efforts to save space.

I have mine to take a screenshot every 60 seconds of the active window and have done so for about 10 years. 

ManicTime tags these screenshots so that they show up when you hover over the timeline. 

I literally cannot imagine life without this feature.

I was hoping ActivityWatch would do this which is why I started looking into it, but it appears you don't even have plans to implement something like this.

I'm pretty sure it's free too.

**Comment by lixaotec** [comment]
not a chance to this feature antymore? sadly forgotten...

**Comment by BelKed** [comment]
https://github.com/Srakai/aw-watcher-screenshot
