### ISSUE TITLE
Improve Contributing Guide

### ISSUE THREAD

**Issue by theshapguy** [ActivityWatch/activitywatch#235]
I really wanted to start contributing to this project, however found it quite hard. 

First of all, this project uses submodules, which is good for code separation, however when I fork this project the submodules forks are not forked. I know this might not be a hassle for people who already have the code setup in their computer, but is a hassle for new contributors.

>  I'm not asking for all these repos in one, except for watchers as plugins, but that would certainly make life easier (I'm pretty sure that won't be possible because of all the breaking changes it would bring). So, an solution could be to write a script [`Ansible` or probably `bash`] that does it all.

Secondly, It would be great if the tools used and `python` version were presented upfront in the README.md fine. I only later found out that this project uses PyQt and had to dig really hard to find the other tools used in this project. Had to look at CI files to find out how everything was connected together.

> It would be great if all the resources were presented in the contributing guide upfront. May be we can bundle all the `install_requires` from setup.py? 

These are just my first impressions when I was forking and wanted to make code contributions, it would be great if we could combine all these resources for a new contributor. There is probably lots of things I missed out.
 
*P.S You guys are doing a great job, I really am digging' this project 👍*

**Comment by johan-bjareholt** [comment]
> First of all, this project uses submodules, which is good for code separation, however when I fork this project the submodules forks are not forked. I know this might not be a hassle for people who already have the code setup in their computer, but is a hassle for new contributors.

It's not too bad, you just need to add the "--recursive" parameter to git clone and it will solve all that for you as described here

https://activitywatch.readthedocs.io/en/latest/installing-from-source.html

> I'm not asking for all these repos in one, except for watchers as plugins, but that would certainly make life easier (I'm pretty sure that won't be possible because of all the breaking changes it would bring). So, an solution could be to write a script [Ansible or probably bash] that does it all.

We have a plan to merge a few of our repositories

https://github.com/ActivityWatch/activitywatch/issues/227

> Secondly, It would be great if the tools used and python version were presented upfront in the README.md fine. 

We do not want the README file to cointain documentation or guides because in that case it would be incredibly long and hard to navigate in, so we have our docs for that. You can see python version in the readme

https://activitywatch.readthedocs.io/en/latest/installing-from-source.html

>  I only later found out that this project uses PyQt and had to dig really hard to find the other tools used in this project. Had to look at CI files to find out how everything was connected together.

You can see a graph of all dependencies here

https://activitywatch.readthedocs.io/en/latest/development.html

and you can see more about the architecture here

https://activitywatch.readthedocs.io/en/latest/architecture.html

> These are just my first impressions when I was forking and wanted to make code contributions, it would be great if we could combine all these resources for a new contributor. There is probably lots of things I missed out.

You seemed to miss out the whole documentation page it seems which holds most of the information about the project.

> P.S You guys are doing a great job, I really am digging' this project +1

Many parts of AcitivityWatch still needs a lot of improvements but the base architecture works very, great to hear people finding it to be useful :)

**Comment by ErikBjare** [comment]
@johan-bjareholt We should probably add those links to `CONTRIBUTING.md` though so that they're easier to find.
