### ISSUE TITLE
Tray icon doesn't show up using Solus Linux/Budgie

### ISSUE THREAD

**Issue by MatthewScholefield** [ActivityWatch/activitywatch#238]
Running the latest release (v0.8.0b6), on Solus Linux, the tray icon doesn't show up. [Here's the stdout logs](https://hastebin.com/sabacutido) and [here's the log file](https://hastebin.com/ureweledip).

**Comment by johan-bjareholt** [comment]
Gtk-Message: Failed to load module "pk-gtk-module"
    Gtk-Message: Failed to load module "canberra-gtk-module"

This is most likely the issue. I am no expert with how tray icons work or why it tries to load the tray icon with GTK even though it's Qt, but this at least indicates that some dependency is likely missing or broken. ActivityWatch is supposed to bundle most dependencies though instead of using system libraries so this likely an issue on our end aswell.

**Comment by ErikBjare** [comment]
I assume this would be [Budgie](https://en.wikipedia.org/wiki/Budgie_(desktop_environment))-specific? If someone could try installing Budgie on another distro like Arch or Ubuntu and replicate that'd be much appreciated.

**Comment by ErikBjare** [comment]
I'm going to close this until someone manages to replicate and see if it applies to all environments running Budgie or just Solus.

**Comment by johan-bjareholt** [comment]
Could be that Budgie just like Gnome 2.26 and above doesn't support trayicons, we should implement aw-qt to use an appindicator instead. 

Similar forum thread:
https://forum.activitywatch.net/t/cant-run-aw-qt-under-gnome/169/4?u=johan-bjareholt

**Comment by ErikBjare** [comment]
@johan-bjareholt Hmm... Does this mean we need to add gtk as a dependency **and** develop (how much?) Gnome/Budgie-specific code? I'd love if someone else could make this in a PR since I don't use Gnome or Budgie myself and they likely make out less than 5% of users.

Hadn't seen that forum post before though, well documented stuff about both Wayland and Gnome. Completely forgot I coded that "missing system tray" message box.

Also, is it just me or does the links to the logs not work anymore? Hastebin doesn't show any logs for me.

**Comment by johan-bjareholt** [comment]
@ErikBjare No, trayicons are deprecated because they are an Xorg thing while appindicators has been recommended for many years and work on both kde, gnome and budgie.

appindicators has been recommended for years in the Gnome world, but personally I didn't know that trayicons were based on Xorg or that appindicators were supported on KDE aswell.

I am guessing something like this is the new recommended way: https://launchpad.net/appmenu-qt5
