### ISSUE TITLE
On the Window detail tab of the Activity area, Options Filter away AFK time is not working

### ISSUE THREAD

**Issue by NachoParra** [ActivityWatch/activitywatch#241]
When I go into the Window detail tab of the Activity area, there is a donut chart at the end of the screen in which we can select if we want to filter away AFK time. If we select it, the AFK is still being shown on the  chart. Is this how it will needs to be working?

![image](https://user-images.githubusercontent.com/30796378/46414644-d4a27700-c723-11e8-8623-d3ffc5aa0b0c.png)

 ActivityWatch Version: v0.8.0b6

**Comment by johan-bjareholt** [comment]
Yeah this is how it is implemented, but I agree that it doesn't really work as you'd expect.

The "Filter away AFK time" button is hidden in the bottom for the reason that we didn't want to remove the feature yet it doesn't really work properly with this "sunburst" chart as we usually call it (maybe donut is the correct term for it though? I don't know). We also don't expect most people to even use this option.

Closing, feels like a fix for this issue is more related to some larger UX and visualization refactor later (it's not really an "issue" per se)

**Comment by NachoParra** [comment]
OK, thanks for the info.
