### ISSUE TITLE
Feature request: Dark Theme for Dashboard.

### ISSUE THREAD

**Issue by JordyScript** [ActivityWatch/activitywatch#253]
It would be awesome if we could have a built in dark theme for the dashboard.

**Comment by johan-bjareholt** [comment]
I also prefer dark webpages and use a Firefox extension to achieve that (darkreader).

To have this natively would be nice to get a better experience, but maintaining two styles is not something we want to spend time on currently since we are making so rapid changes currently to the UI.
Once the webui gets more stable and changes less often I'll consider this though!

**Comment by ErikBjare** [comment]
Discussion moved to [the forum](https://forum.activitywatch.net/t/dark-theme-for-web-ui-and-android-app/274). Vote on the feature there so we can know how much interest there is!

**Comment by phanirithvij2000** [comment]
It has been added but there wasn't a new release since that commit (~month ago) https://github.com/ActivityWatch/aw-webui/pull/307

**Comment by ErikBjare** [comment]
@tsilvs This was completed a long time ago. Have a look in the settings.
