### ISSUE TITLE
Can i get rid of the Terminal window?

### ISSUE THREAD

**Issue by evaldasjab** [ActivityWatch/activitywatch#260]
Dear developers, i'm excited to try your application out because i suspect that RescueTime doesn't count durations properly and i don't like the idea of my data on their servers.

On MacOS Sierra I launched `./aw-qt` in the Terminal and the AW icon appeared in the system tray.
But the Terminal window (actually, two windows now) is still on and if i close it, the icon disappears and i believe the app is not running any more.
Is it possible to keep the app running without Terminal windows?

**Comment by johan-bjareholt** [comment]
We fixed that on Windows a few months ago which was trivial, but it's harder to do on macOS since double clicking an normal executable opens it in a terminal window.

We would have to do to solve this is to make a .app bundle and automate the creation of it.
When making it into a .app bundle dependencies are also probably going to break and the location of the watchers will be wrong, so there's probably a lot which needs to be changed.

https://stackoverflow.com/questions/1596945/building-osx-app-bundle

**Comment by evaldasjab** [comment]
While you are making an .app bundle, maybe there is a workaround?
I [found](https://apple.stackexchange.com/questions/133087/how-to-prevent-the-application-launched-in-terminal-from-undesirably-exiting) a command `nohup ./aw-qt & exit` which lets you close Terminal and keep the AW app running.
But the icon "aw-qt" stays in the dock...

**Comment by johan-bjareholt** [comment]
Yeah, there are workarounds that are not user friendly.

nohup essentially makes the aw-qt process into a daemon which is a suitable solution.
This could possibly also be implemented directly within aw-qt, but setting that by default would not be wise since it seems likely that someone could by mistake open multiple instances of aw-qt.

Another option would be to make the macOS automator start aw-qt when you login, since that can run programs by itself I believe.

**Comment by exoji2e** [comment]
My [PR](https://github.com/ActivityWatch/aw-qt/pull/42) removes the dock icon. If you don't want to wait for a new release: 
- clone activitywatch
- checkout my branch from your aw-qt repo inside activitywatch
- run `make build DEV=true`
- restart aw-qt
