### ISSUE TITLE
high cpu usage of aw-watcher-window after several days' running

### ISSUE THREAD

**Issue by Novite5** [ActivityWatch/activitywatch#262]
This problem occurs after more than two days running, in the meantime, the OS has suspended once. After killing and restarting the process, the CPU usage return to normal level.

Htop displays:
![grafik](https://user-images.githubusercontent.com/16817335/50943386-34e54980-14c7-11e9-94a9-b6ff4cc545f9.png)

In the log file repeatedly display this information: 

> [WARNING]: Inserting event that has a older timestamp than previous event!

## Environment
 - ActivityWatch version: v0.8.0b7-2
 - OS: Archlinux x86_64 kernel: 4.20.0-arch1-1-ARCH

**Comment by johan-bjareholt** [comment]
Hm, that's odd.
We need a stacktrace during the budy part of the code or profile it to have a clue where it might take up so much resources.
I really have no idea where this might occur in the code since it aw-watcher-window really doesn't do anything resource heavy at all (takes 0-1% cpu for me).

So, you have two options to help us find the root cause:

- Run aw-watcher-window normally outside of aw-qt and log to a file, exit it when it's broken again and you'll see a stacktrace, hopefully where the the busy code is (very likely)
- Run aw-watcher-window outside of aw-qt from source with the cProfile python profiler (python3 -m cProfile ./aw-watcher-window.py)

**Comment by Novite5** [comment]
I'm sorry. After a week of trying, I haven't reproduced this.
I guess it might have something to do with firefox crash.

**Comment by Novite5** [comment]
Didn't occur again. It might be only an odd case.

**Comment by phuntik** [comment]
Hello dears.
Got the same problem of whole core usage (Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz) after a several days.
Are there any useful logs/traces I can provide to you guys before restarting aw?
Other aw apps are running at low point.

```
PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
20   0  119156  29468   5124 R 100.0   0.2   2764:08 aw-watcher-wind

3451143  0.0  0.0   2608   344 ?        S    Jan09   0:00 /bin/sh -c aw-qt
3451149  0.0  0.2 584392 35604 ?        Sl   Jan09   2:35  \_ aw-qt
3451206  0.2  0.2 270336 37032 ?        Sl   Jan09   9:45      \_ /opt/activitywatch/aw-watcher-afk/aw-watcher-afk
3451207 62.7  0.1 119156 29468 ?        Rl   Jan09 2769:02      \_ /opt/activitywatch/aw-watcher-window/aw-watcher-window

```
ubuntu 20.04, i3wm 4.22

**Comment by cate02** [comment]
I believe I also encountered this just now
Installed it about a week ago
W11 5900x according to task manager 75% CPU utilisation with all 24 threads highly saturated (very rare for all threads to be in use)
Stopping activity watch in the system tray returned cpu usage to normal, and restarting it again was normal too.
I often have my computer on for sometimes weeks at a time as I often put it to sleep opposed to shut down/restart
