### ISSUE TITLE
Client-side caching for weekly/monthly/yearly reviews by splitting into months/weeks/days

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#264]
In my notebook experiments I frequently run >30 day queries, to reduce the time to run these every time I want newer data I started doing clever things like splitting the period into periods of (T-30 days to start of today) + (start of today to now). The query itself it then simply memoized using joblib.

This worked fine, but it still required a huge (>30 day) query every new day I ran the query. So as I realized this might be an interesting avenue to explore more generally for aw-webui, I came up with the following:

```python
events = []
for start, end in split_into_days(since_day, now):
    events += get_events(since=start, end=end)
```
This solved the problem without issues, as `get_events` is memoized by its arguments. I think (but might be mistaken) that this is similar to an [interval tree](https://en.wikipedia.org/wiki/Interval_tree).

Anyway, I definitely think this is the way to go forward. I'll try and publish my updated notebook sometime soon, where there is significantly more detail. 

Would help solve the primary issue of #189 without implementing server-side caching.

**Comment by johan-bjareholt** [comment]
> The query itself it then simply memoized using joblib.

We still need caching in aw-webui, that's the reason why I prototyped the cache server-side to begin with.

**Comment by ErikBjare** [comment]
@johan-bjareholt Yes, what I'm proposing is adding this type of caching in aw-client-js.

**Comment by ErikBjare** [comment]
> Where will the cache be saved when run in a browser? How does this make invalidation easier?

There are a few options I can come up with where most of the work would have been done for us:

 - Split up the query into subqueries and enforce aggressive caching through the `Cache-Control` request header, an identical query URL would then hit the cache and not requery. 
 - Use something like [`CacheStorage`](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage).
   - Invalidation could be triggered on clicking the "Refresh" button (or a special "Clear cache" button), or when the cache ages.
 - Store the results of a given query in localStorage (a bad option in the presence of CacheStorage)

> If we cache every month, how are we then supposed to use these cached values to do the same summary but for a year? Would this mean transformations in the client?

I realize now that the queries used in my notebook is a bit different from the queries used in aw-webui.

In my notebook my query always returns a range of events (AFK-filtered, including browser events, etc) and then I do all my grouping, classification, etc on the client side. Caching therefore becomes easy to do in the way I proposed, since it's basically just concatenating several event-series. But caching of summaries is obviously (in hindsight) harder to build a generalized caching solution that is based on splitting up the query into subqueries, since the merging operation would be more complex (and could vary wildly).

This is an obvious miss with my proposed solution, but maybe you could specify on the client-side how the subquery results should be merged for the special cases?

**Comment by johan-bjareholt** [comment]
> In my notebook my query always returns a range of events (AFK-filtered, including browser events, etc) and then I do all my grouping, classification, etc on the client side. Caching therefore becomes easy to do in the way I proposed, since it's basically just concatenating several event-series. 

The problem with this is that the browser events for a whole year would still be way too large I believe.

> But caching of summaries is obviously (in hindsight) harder to build a generalized caching solution that is based on splitting up the query into subqueries, since the merging operation would be more complex (and could vary wildly).

Yes, it's a lot harder and is why I gave up after a while.

> This is an obvious miss with my proposed solution, but maybe you could specify on the client-side how the subquery results should be merged for the special cases?

My idea for the previous prototype worked like this:
- Create a short-term query of only duration summaries (a week to a month long).
- Give this short-term query a name
- Create a second query which merges these queries (average duration, summed duration etc. depending on the field).

This second query needs that the short-term query has a name or some other kind of identifier so it can know which sub-query to query (and can be either cached or not).

This second-query could technically be done on the client-side though since they will likely be rather simple, just summing and average on som numbers and some sorting on lists. Still though, for the same reason that it's annoying to re-write transforms in many languages it will be annoying to re-implement this for every client which is why I think that the server-side solution is better.

The reason it's important that we cache in smaller intervals before doing a whole-year summary is because if we want to see the summary for the current year we don't want to re-query everything from the past year, only querying the past week/month would be a huge performance improvement.

Another concern is, what to do with timezones? (for example if a user changes timezone and all caches are invalidated) An sub-optimal solution but acceptable solution would be to skip them altogether might be an option since we are talking about such huge timeperiods as a month to a year.

**Comment by ErikBjare** [comment]
This is no longer needed as of v0.8, closing.
