### ISSUE TITLE
Server is not able to start on Windows 7

### ISSUE THREAD

**Issue by daynialDK** [ActivityWatch/activitywatch#306]
I have copied complete folder in my PC
when I try to run it on my windows 7 it crush
when i click solve by internet it show new error about ntll.dll
and then it show any other error

 - ActivityWatch version: v0.8.0b9
 - OS: Windows 7

please help

**Comment by ErikBjare** [comment]
There is already an issue on this: https://github.com/ActivityWatch/activitywatch/issues/91

We don't support Windows 7, sorry.

**Comment by daynialDK** [comment]
I am not building the code.
I am running the aw-qt.exe application.

#139 this error shows that application can be run on windows 7

**Comment by ErikBjare** [comment]
>I am not building the code.
>I am running the aw-qt.exe application.

That's what the issue says the problem is. It would most likely work if you run it from source. But setting up the development environment can be a bit tricky on Windows (which is one of the reasons why nobody is picking it up).

>this error shows that application can be run on windows 7

Not quite, it says you could run it on Windows 7 **in 2017**. So you could probably run an old version if you really want to.

>and if this does not support on windows 7, so is there any plan to resolve it ?

As I said in #91, unless someone rises to the challenge and picks it up, it won't be solved. And I don't expect that to happen, since Windows 7 is nearing it's End of Life (January 14, 2020).

**Comment by sergeevabc** [comment]
@ErikBjare, decision of Microsoft, Silicon Valley's hygemon, not to support any of its apps is their choice. The app itself, or OS in this case, works and will work fine for the foreseeable future as long as there are suitable hardware and electricity. For example, I installed Windows 7 back in 2009 and still delivers everything I need. And there are many of us who think in a similar way on the globe, beyond the so-called golden billion chaps who shiver out of fear of not getting a narcotic dose of shiny security updates.

The real question is not about their choices, but about yours. What has changed so much in the ActivityWatcher's code that it cannot be compiled for Windows 7? Is it really more complicated than, for example, one of super-popular games like Crysis, Fallout, or Left4Dead? They all run fine on Windows 7, whereas ActivityWatches throws errors as follows.

![image](https://user-images.githubusercontent.com/373718/201511774-30403f9d-1c3f-4bb2-84bb-38dd8c65be06.png)

**Comment by ErikBjare** [comment]
@sergeevabc Win 7 is not supported because (1) we have no way to test it, and (2) we depend on other software (Python, PyInstaller, etc) which have all dropped Windows 7 support a long time ago. It's that simple.

If you want to, feel free to [build it yourself](https://docs.activitywatch.net/en/latest/installing-from-source.html), as I've already suggested above, if you think it shouldn't be that difficult (but a warning: others have tried, and failed). Not as easy as you think.

>The real question is not about their choices, but about yours.

What choice? If you'd read the previous messages & links here you shouldn't have any questions. My hands are tied.

If I had a quick & reasonable way to fix this I would, but I don't. I'm not spending what is probably upwards of a hundred hours (if possible at all) to support maybe 3-4 people who are stubborn about updating their outdated operating system.

>What has changed so much in the ActivityWatcher's code that it cannot be compiled for Windows 7?

Nothing in the code per se, but several of the upstream dependencies we depend on.

>Is it become more complicated than, let's say, one of the popular games like Crysis, Fallout, or Left4Dead?

Yes. They have a static/finished codebase, a Windows 7 build server somewhere (if new builds are even made), and a paid support team to maintain it all. Needless to say, I don't.

Locking this issue, please don't bring it up again (at least not with that tone).
