### ISSUE TITLE
Tracking Amazon videos time (TV shows), ideally fullscreen mode

### ISSUE THREAD

**Issue by miesismore** [ActivityWatch/activitywatch#315]
Would be nice to be able of tracking Amazon videos time (TV shows), ideally fullscreen mode

If not possible in full screen mode in normal mode would be nice to.

**Comment by miesismore** [comment]
It's weird, in Timeline i have the record of 42 min of Amazon video log, but then this is not shown anywhere in Activity tab...
![CAPT-0005](https://user-images.githubusercontent.com/28994304/69480112-adfe3e80-0e04-11ea-83e7-4634cbacac09.png)

**Comment by ErikBjare** [comment]
That is because there wasn't any mouse or keyboard input detected during
that time (see the AFK bucket in the timeline).

We have a working prototype/PR in aw-webui that will automatically detect
audible tabs as active, which will solve your issue, but there's no ongoing
effort to fix the remaining issues before it can be merged, so it could
take a while.
