### ISSUE TITLE
Activity time isn't accurate

### ISSUE THREAD

**Issue by partulaj** [ActivityWatch/activitywatch#332]
I just notice that the my activity time of yesterday was wrong, ActivityWatch say I only spent 13min 11s watching my show but I watch a full 24min episode and I also had the same problem today.
I watched my video using MPC-HC in fullscreen could it be related to the fact I watch in fullscreen ?

Activity watch version 0.8.3

**Comment by johan-bjareholt** [comment]
It's due to the fact that there's no way to know if someone is looking on the screen or not.
It's indeed very annoying when you are watching movies as we then assume that you are away.

There's no way to know, we have considered doing things such as checking if we have output from the speakers or similar and then assume that you are at the computer, but no-one has actually went and implemented such a feature.

If you however find that activity time is inaccurate when you are using your mouse or keyboard please feel free to report.

**Comment by ErikBjare** [comment]
See #261 for the discussion that Johan mentioned.
