### ISSUE TITLE
Travis CI build config validation suggestions

### ISSUE THREAD

**Issue by cclauss** [ActivityWatch/activitywatch#384]
![Screenshot 2020-03-22 at 09 32 40](https://user-images.githubusercontent.com/3709715/77245635-58a23480-6c20-11ea-8cd8-ae2f9403ca5b.png)

**Comment by ErikBjare** [comment]
We are aware of this, it's inconsequential and the deploy/skip_cleanup warnings are even wrong as they *only* work in dpl v2, which isn't yet used by Travis.

We're also in the process of investigating moving over to GitHub Actions due to frequent issues with Travis, feel free to check it out and leave suggestions there: #382

**Comment by cclauss** [comment]
On the GitHub Action front, I contributed #383 which I have used successfully on other repos.
