### ISSUE TITLE
release archive doesn't contain systemd service

### ISSUE THREAD

**Issue by kovetskiy** [ActivityWatch/activitywatch#403]
**Is your feature request related to a problem? Please describe.**
The release archive that can be downloaded from github releases doesn't contain systemd's .service files.

**Describe the solution you'd like**
Put systemd .service files for aw-server (not only rust one)  and all known watchers.

**Additional context**
Currently, aur's activity-watcher-bin package doesn't contain systemd services and it means that users can't really use it unless they write their own systemd services or do something like `aw-server &` in xinitrc or somewhere else. The package downloads releases from this repository releases so the problem should be fixed here.

**Comment by ErikBjare** [comment]
We can't make systemd services for the watchers since they require running within an X session. This is why the recommended way to run ActivityWatch is aw-qt, with autostart on Linux done using a `.desktop` file (placed in the autostart folder by the AUR package). 

Since aw-server will be deprecated in favor of aw-server-rust soon we are unlikely to create an official systemd service for it. You are welcome to write your own.
