### ISSUE TITLE
Incorrect activity time (time missing) 

### ISSUE THREAD

**Issue by fdawans** [ActivityWatch/activitywatch#440]
I am using AW 0.9.0 on Android 10 and the activity time reported in the app is much much lower than the actual time. The app is reporting 30 minutes but it should be a few hours.
Any help? 
Thank you.

**Comment by ErikBjare** [comment]
This might be a known bug. ActivityWatch rarely wakes your phone to sync the time spent, but if it was a while since that job ran then you may not see the data for the entire day yet.

If you open the Activity view, wait for 30s, and then click the refresh button, does the total time increase? If so, that would indicate that your missing activity is still being loaded into ActivityWatch in the background.

This happens most of the time that I open the app though. Although the data is never older than last night, so it appears the job runs at least daily (on my phone, likely affected by power settings of your Android ROM).

Fixes could be to:
 - Speed up the job that creates heartbeats from the Android API (pre-merge heartbeats, for example). 
 - Make sure the job has completed before showing the Activity view.
 - Indicate the data is stale/being updated on the Activity view.

**Comment by fdawans** [comment]
Yes, time is increasing but I guess it stops recording a few times a day. Recorded time is roughly equal to only half of my total screen on time.

**Comment by ErikBjare** [comment]
This should be (mostly) fixed by https://github.com/ActivityWatch/aw-android/pull/40 which will be included in the next release.

Closing.
