### ISSUE TITLE
Use inside of vim which is running in the WSL?

### ISSUE THREAD

**Issue by aasutossh** [ActivityWatch/activitywatch#451]
I installed the plugin but it probably can't see the AW server.

**Comment by johan-bjareholt** [comment]
I assume you mean the aw-watcher-vim watcher?

Probably?
There should be errors in vim if it can't connect (shows a message in the bottom).
Also, if there's nothing showing in the web-ui in the editor tab it doesn't work either.

But anyhow, if it doesn't work there's not much we ActivityWatch developers can do about it. It should be possible to work around since the only thing the watchers need to be able to talk to aw-server is to connect to the localhost port 5600. If that's not available it's a question of how to expose a port from the windows host to WSL which I'm sure is possible.

According to this comment it seems that nothing should be needed for aw-watcher-vim to work in WSL (WSL2 I don't know however)
https://github.com/Microsoft/WSL/issues/1032#issuecomment-244160207

**Comment by aasutossh** [comment]
I am using WSL 2. Sorry for misinformation. WSLs are set up weirdly. Anyway, thank you.
