### ISSUE TITLE
merge several hosts into one?

### ISSUE THREAD

**Issue by alexriabtsev** [ActivityWatch/activitywatch#454]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **MacOS Big Sur 11.0 Beta (20A4299v)**: 
- **ActivityWatch 0.9.2**: 

## Describe the bug
<img width="384" alt="image" src="https://user-images.githubusercontent.com/8425396/87343436-86a3df80-c555-11ea-8ea8-a4dc3836c299.png">
I have several "hosts" under Activity menu. Is there any way to merge them?

**Comment by johan-bjareholt** [comment]
It is possible by exporting changing the export file and then importing, but not in the UI.

We have not implemented this yet because it hasn't been an issue and if merging buckets wrongly it will create broken data so it is an action which needs to be done with caution.

**Comment by alexriabtsev** [comment]
@johan-bjareholt thanks for reply!
How can I do that via export/import? docs?

**Comment by nicolae-stroncea** [comment]
@alexriabtsev I think you could do that by exporting everything to JSON, cutting all of the events from one bucket and pasting them under the other, deleting the unnecessary buckets, and reimporting. This would be simplest, quickest way. More advanced ways would be to read JSON into python script and do the same changes there programmatically, or by changing the bucket_id directly in the database using SQL queries

*Note*: If these hosts ever ran in parallel, there may be issues because you have multiple events occurring simultaneously.

**Comment by ErikBjare** [comment]
I wrote a Python script that inserts all events from one bucket into another bucket, after checking for overlap (which you shouldn't have if it was caused by a changing hostname): https://github.com/ActivityWatch/aw-client/pull/50

I used it for my duplicate buckets caused by hostname issues, and it seems to work fine but please backup your stuff before running.
