### ISSUE TITLE
Constant CPU usage on macOS 10.15.5

### ISSUE THREAD

**Issue by danielzuegner** [ActivityWatch/activitywatch#472]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue
I've just started using ActivityWatch on macOS 10.15.5. I've noticed that when AW runs, the process "System-Events" continuously uses ~15% CPU on my MacBook Pro 13" 2015 (see screenshot), and even leads to the fans constantly spinning quite audibly in clamshell mode. 

![~15% CPU](https://user-images.githubusercontent.com/22178797/90417198-b6de2100-e0b3-11ea-9589-2d9c09707218.png)

Disabling `aw-watcher-window` made the CPU usage drop to almost zero. 

Is this normal behavior? Is there anything I can do to reduce the CPU usage but still track my usage?

**Comment by johan-bjareholt** [comment]
Probably related to this? https://github.com/ActivityWatch/aw-watcher-window/issues/45

**Comment by danielzuegner** [comment]
Tanks for your reply. I've had a brief look a the issue you mentioned. I checked my Console log, and there are no similar messages to the ones in the other issue. The process "System Events" (with high CPU usage for me) emits these messages roughly every 2 seconds (not sure if relevant):

![activitywatch3](https://user-images.githubusercontent.com/22178797/90488347-108a2e00-e13c-11ea-8e37-991b546b9084.png)

**Comment by danielzuegner** [comment]
It seems like the CPU usage increases with the number of windows / tabs, is that possible? Closing all windows made the CPU usage drop to ~3-5%, and re-opening some windows gradually adds CPU load (as it seems).

**Comment by johan-bjareholt** [comment]
> It seems like the CPU usage increases with the number of windows / tabs, is that possible? 

The thing is that this is very hard for us to know because it's not ActivityWatch itself taking up the CPU resources but a macOS process which is not open source.

The only thing I know is that our way of getting the focused window with aw-watcher-window only asks for the focused window, whether macOS internally needs to iterate over all windows to find that however we can't know.

As stated in the other PR though there's a PR to rewrite the whole macOS backend for aw-watcher-window which hopefully will make things more reliable, I think that's our best shot at improving/fixing this. https://github.com/ActivityWatch/aw-watcher-window/pull/40
