### ISSUE TITLE
"Uncategorized dark matter"

### ISSUE THREAD

**Issue by synergiator** [ActivityWatch/activitywatch#481]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue
Hi there, I use ActivityWatch since the beginning of this month and like it a lot! Over time, 

I have extended the categories for better reporting. However, over time I have noticed that the "Uncategorized" category still has over 50% of the time, but the top-level entries there does not seem to account for the 50%.

That is, I would like to find out, what does "Uncategorized" being accroding to the sunburst over 50% of the time include else; I understand there must be a "long tale" of things, but currently the first top-level entry in the "week" view mode accounts for just 3 hours, followed by 2x1 hours, then 2x30 minutes and so on.

Please share if you have an idea how to assess this.

**Comment by johan-bjareholt** [comment]
On the bottom of the page there is a button to filter by category, select "Uncategorized" there and you'll see only what no rule has matched. That way you can easily find what more rules you need to make to get "Uncategorized" to be smaller.

**Comment by synergiator** [comment]
@johan-bjareholt thanks for your asnwer - this is what I have tried to explain: 

* notice how big is "Uncategorized" say for a week 50% = 20h 
* select "Uncategorized"
* review what is shown, build a sum of top 6 entries = 4h
* how to find remaining 15 hours? (entries from 7th on get much smaller so that it doesn't look all the long tail can really make up to 15h

Possibly I could do a similar query to see exact values on some internal database component of ActivityWatch?

**Comment by ErikBjare** [comment]
>how to find remaining 15 hours? (entries from 7th on get much smaller so that it doesn't look all the long tail can really make up to 15h)

I'd expect that the long tail really does add up to 15h in that case. The vast majority of events are <1 min (as you can easily see in the "Raw Data" view). Over thousands of events, this adds up.

>Possibly I could do a similar query to see exact values on some internal database component of ActivityWatch?

The internal values won't exactly match the ones shown in the Activity view due to transforms like flooding (which remove small gaps between events). I'm not sure how helpful it'd be, but you can always try to run your own query using the query explorer.

If you open `dev tools (F12) -> network` in your browser and inspect the query request you should see an example of the query that runs. There are currently three of them, one for the main query, one for the browser events, and one for the total active time.

---

Regardless, if most of your uncategorized activity is from web browsing, I can at least say that in the future there'll be a way to categorize by URL/domain, which should make it a lot easier to write rules that accurately match uncategorized events where the site doesn't provide an informative title.

**Comment by synergiator** [comment]
Agree that additional categorization by URL/Domain could indeed address this! Nowadays much of screen time happens using web browser.

**Comment by synergiator** [comment]
corresponding feature request to allow mapping of domains to categories
https://github.com/ActivityWatch/activitywatch/issues/352
