### ISSUE TITLE
Warning on AlternativeTo

### ISSUE THREAD

**Issue by timharek** [ActivityWatch/activitywatch#493]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

The app is marked with a warning on [AlternativeTo](https://alternativeto.net/software/activitywatch/)
> This application may not be safe:
> FileRepMalware and Trojan detected by VirusTotal.

![Skjermbilde 2020-10-04 kl  16 59 08](https://user-images.githubusercontent.com/5453010/95018955-edbbc680-0662-11eb-84ec-f5ebf838ad66.png)

**Comment by ErikBjare** [comment]
Thanks for bringing this to our attention. We've known that some antivirus systems flag it as malicious for quite some time (see https://github.com/ActivityWatch/activitywatch/issues/181), but one of the links in the comments provided a great summary of *why* they do so: https://www.hybrid-analysis.com/sample/beb047cb7583df66301493c613afe0d7bf6c62b5445eb38797b6fcf38d239afe/5e7cd780c49eaf4be46cde62

I'll mention it in the other issue, but I'll close this one since I'm not sure what we can do about it.

**Comment by ErikBjare** [comment]
I emailed them, and they've now removed the warning. Thanks for reporting!

**Comment by timharek** [comment]
No problem, thanks for the amazing tool and keep up the good work! 😎

**Comment by johan-bjareholt** [comment]
Seriously thanks a huge lot for reporting this @timharek, the last thing we want for the project is for it to be falsely seen as insecure or malware!
