### ISSUE TITLE
Won't update web browser data; using a Chromium based browser

### ISSUE THREAD

**Issue by TheOrigins** [ActivityWatch/activitywatch#503]
Hey! So I've installed the extension, and I know you don't offer support for browsers other than Firefox and Chrome, but would like to know if there's something wrong on my end. The bucket appears, and is catching data, but when I go to activity, it says "No data". Tried this on Chromium and on Edge (the new version that supports Chrome extensions and runs on the same engine). 
Hopefully it's a mistake on my end / it's something you can help me with. 

Cheers! Thank you for the amazing app.

**Comment by johan-bjareholt** [comment]
We do support Chromium, at least it works on Linux. Maybe it just doesn't work on windows?

The thing is that to support a browser we need to know the appname it has in the window watcher because webextension APIs doesn't allow us to know whether the window is focused or not so we fuse that data to circumvent that (so the window and afk watchers need to run simultaneously too, which they do by default).

Take a look at your appname of your browser and see if it's inside the list below. If it's not it needs to be added and we'll add it so it works in the next version of ActivityWatch. The appname can either be found on the "Top Applications" list in the "Activity" tab or in the window bucket under the "Raw Data" tab. 

https://github.com/ActivityWatch/aw-webui/blob/03a1242dc88d562fd390172fd2157cf79ad6abbd/src/queries.ts#L100

**Comment by TheOrigins** [comment]
Both the Chromium and Edge are already in the list, I'm not sure why it's not working. 
The Edge watcher seems active ("aw-watcher-web-edge") but it still says no data.

**Comment by johan-bjareholt** [comment]
What were the app Ames i asked about earlier? Are they exactly "edge.exe" for example or something else?

**Comment by ErikBjare** [comment]
It should be noted that `edge.exe` was added in April, with v0.9.2 released in May, so it'll be in the next release. Since we don't have `chromium.exe` in there I assume that could be an issue specific to Chromium on Windows, and it'd have to be added.

But yeah, we need the exact strings @TheOrigins.

**Comment by TheOrigins** [comment]
Oh sorry, I misunderstood. Yes, it's chromium.exe. Can you also please add msedge.exe? That's the appname according to the web UI. Thank you so much, both of you!

**Comment by ErikBjare** [comment]
@TheOrigins I added `chromium.exe` in https://github.com/ActivityWatch/aw-webui/commit/541e99cc1715c20d199ba9353de4d1008162cc94, and yes, since `msedge.exe` was already in there it'll be in the next release.

**Comment by Ljuk67** [comment]
Hi there, I am on Linux Mint 22 Cinnamon + Chromium Version 136.0.7103.92 (Official Build) (64-bit). The application name appears as "Org.chromium.Chromium" - can you add it to the list please? 

The watcher is tracking my Tab Titles, but not the URLs.

**Comment by BelKed** [comment]
Already added in https://github.com/ActivityWatch/aw-webui/pull/623, will be added to the next release :)

**Comment by Ljuk67** [comment]
that was fast, thanks! :D
