### ISSUE TITLE
Child categories do not depend on parent rules

### ISSUE THREAD

**Issue by las-nsc** [ActivityWatch/activitywatch#517]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

(It's hard to know what keywords people might use, but I tried a few and only saw suggestions)

- **OS version and name**: Windows 10 20H2
- **ActivityWatch version**: v0.10.0

## Describe the bug
Activities aren't correctly categorised when the same sub-activity filter is used under multiple activities

## To Reproduce
1. Add 2 activities with different patterns (for example two project names)
2. Add a sub-activitity to each with the SAME patterns (for example an IDE, Mail Client or Browser name which might be used for either)
3. Use the application to trigger both top level patterns.
4. Observe all time logged against first activity, not split between both.

## Expected behavior
Filters should be applied in order from the root to the leaves, with AND logic.
This means the time spent in the same application on each activity should be grouped separately.

## Additional context
I'm not sure what the behaviour would be when not applying a filter on multiple activities. I suppose it would have to be assigned to the first activity it fits in. Not having a filter seems only seems useful as a 'default' in which case only one should be needed.

**Comment by ErikBjare** [comment]
It's not really correct to think of categories as "filters". 

To clarify the actual behavior: Each category rule (regardless of depth) is used to classify events. If an event matches a rule, then they are assigned the category. If another rule of greater depth (could be anywhere [1]) matches later, it is chosen instead. This process continues until all rules have been tested on the event.

[1]: This might change in a later version, where rules could have an explicit `priority` set.

>Filters should be applied in order from the root to the leaves, with AND logic.

This is therefore not the case, and intentionally not how it's designed.

**Comment by las-nsc** [comment]
That seems very unintuitive and not very helpful then.

**Comment by ErikBjare** [comment]
Ah, that makes more sense. I didn't realize your issue was with the filtering that happens on the Activity view, I thought you meant filtering was how categories were applied to events in the first place. Also, the title of the issue seems to imply the actual categorization step was going wrong, which was confusing.

>That seems very unintuitive and not very helpful then.

Not very nice nor helpful to hear you say that, but at least you're the only one to say so :man_shrugging: 

>'Filter' means to apply a rule which determines whether something is included or not, so it IS a filter, but I've changed it to say 'pattern' anyway.

The Activity view indeed performs simple filtering (as described in the UI), but the preprocessing step of applying rules to categorize events is, as I explained before, not simply filtering (although a part of the operation can be expressed as a filter).

---

Alas, I'm still at a loss as to what you're finding wrong with the current approach. And I'm not entirely sure what you mean by "Filters should be applied in order from the root to the leaves, with AND logic". 

Before I thought you meant "*Rules* [1] should be applied...", but if you're talking about filtering it doesn't make sense to me, there is no "apply in order", there is only "filter for events with this category and any child categories".

[1]: To clarify terminology, each category has a rule, and a rule can a regex rule, which in turn has a pattern.

**Comment by las-nsc** [comment]
I wasn't intending to be negative, I was just saying it how it was. I applied rules to categories and sub-categories as I would have intuitively expected it to work, and it doesn't to what I expected, therefore unintuitive an unhelpful (at least to me, and I don't often have issues with things behaving in an unintuitive way).

If you follow the reproduction steps it should make sense what I'm trying to describe. and the time spent in the same application could be split because it would be two instances and therefore create separate events.

My expectation would be that the bottom level category rules are used to put events into buckets, then that process is repeated using the nested categories in a recursive manner. Therefore as each rule is applied to the filtered events of a previous rule it's 'AND logic', and they are 'applied in order from the root to the leaf'. What specifically sounded unhelpful was that events shouldn't ever have their category assignment changed.

I hope that's clearer, and I'm sorry if my terminology isn't quite right.

**Comment by ErikBjare** [comment]
>I wasn't intending to be negative, I was just saying it how it was.

No worries, I was perhaps a bit stressed yesterday and took it personally when you didn't mean it to be. All good :slightly_smiling_face: 

>My expectation would be that the bottom level category rules are used to put events into buckets, then that process is repeated using the nested categories in a recursive manner. Therefore as each rule is applied to the filtered events of a previous rule it's 'AND logic', and they are 'applied in order from the root to the leaf'.

This behavior would lead to much more complicated categorization rules as you'd have to consider the entire ancestor chain when writing rules (instead of just writing a rule that precisely describes the child category). It would, for example, not allow having a parent category without a pattern (as is the case for some of the default categories like `Media` and `Comms`) since they never match anything, and therefore never their children either.

So if I now understand you correctly, you are trying something like:

| name                   | pattern | 
|------------------------|---------|
Project 1                | `project1`
Project 1 -> Email       | `Gmail`
Project 1 -> Code        | `VSCode`
Project 2                | `project2`
Project 2 -> Email       | `Gmail`

Which would indeed not work as you expect it to. But you can try something like this instead:

| name                   | pattern | 
|------------------------|---------|
Project 1                | `project1`
Project 1 -> Email       | `(?=.*project1)(?=.*Gmail)`
Project 1 -> Code        | `(?=.*project1)(?=.*VSCode)`
Project 2                | `project2`
Project 2 -> Email       | `(?=.*project2)(?=.*Gmail)`

This uses the lookahead operator in regex (https://stackoverflow.com/questions/469913/regular-expressions-is-there-an-and-operator) to accomplish the `AND`-type logic/funnel you expect.

>What specifically sounded unhelpful was that events shouldn't ever have their category assignment changed.

This might seem so, but from my perspective, it's more helpful/flexible than being forced to structure your category rules as a funnel.

>I hope that's clearer, and I'm sorry if my terminology isn't quite right.

It is very clear now, thank you for bearing with me :+1:

**Comment by johan-bjareholt** [comment]
There has been one person before which asked a similar thing, see the following thread in the forum

https://forum.activitywatch.net/t/having-subcategories-really-be-subcategories-partitions-of-the-parent-category/625

**Comment by las-nsc** [comment]
After you said it wasn't designed to work as I expected I changed my patterns to something similar to the regex you suggested, and it does work like I wanted now.

I see how the way I expected it to work would be more rigid and restrictive of how you can group events together if they don't all have a pattern in common. For me, that's sort of what I want but I guess not everyone will use it like that.

I do feel that it's still a bit unintuitive, and I think that what might be clearer is for categories to have a pattern filter OR sub-categories rather than both, and when changing a leaf to a branch, a 'default' leaf is created below it.

Starting with:

|name|pattern|
| --- | --- |
|Project 1| `project1`|
|Project 2| `project2`|

Adding a sub-category to project 1:

|name|pattern|
| --- | --- |
|Project 1| *disabled* |
|Project 1 -> Foo | `foo` |
|Project 1 -> default  | `project1`|
|Project 2| `project2`|

To me, and I would think most people with some technical background who didn't know this project better, a hierarchy implies inheritance, when in reality it's more of a grouping with some implicit behaviour.

**Comment by ErikBjare** [comment]
>To me, and I would think most people with some technical background who didn't know this project better, a hierarchy implies inheritance, when in reality it's more of a grouping with some implicit behaviour.

From the users I've talked to, this impression is pretty rare. In many contexts, a hierarchy does not imply inheritance (and especially not what the child inherits, nor how).

There are a lot of ways to solve the UX problem that's really at the core here (including what was suggested in the linked forum post), but I think that if it's easy to work around by changing your regex patterns a bit, then that's good enough. 

It would probably be a good idea to write some docs and add a link to it from the interface, so people can see examples and understand the underlying process better.
