### ISSUE TITLE
My afk watcher doesn't work 

### ISSUE THREAD

**Issue by shadiow6** [ActivityWatch/activitywatch#519]
My entire timeline says "not-afk"even when I go afk for more than 3 minutes and the program tracks stuff like explorer.exe (Program Manager) and Log Screen.exe or something like that even when I go afk on desktop or when I put my pc into log screen/sleep.  I have tried turning off every program in my pc and go afk and it still persists (afker watcher module is activated). I don't know much about pc but a simple explanation would be appreciated. Also, I would like to delete and clean install the program again but the settings and everything still stays the same after reinstalling, so how do I do it?

**Comment by johan-bjareholt** [comment]
We've had people report issues like this a couple of times before, but in those cases it's been other applications or hardware interfering with activitywatch.

An example of hardware could be an mouse or gamepad that slightly twitches even though it's not moving so ActivityWatch will think that you're always at the computer.

An example of software would be some third party application faking mouse/keyboard/gamepad activity for some reason in the background without the user knowing it and since ActivityWatch can't know whether it's you or the application making the movement it will be counted as not-afk.

It's not certain that it's one of these two issues of course, but it's two tips to start with at least.

**Comment by shadiow6** [comment]
Alright I have unplugged all usbs from my pc and it seems to work now... Have to live with it I guess

**Comment by johan-bjareholt** [comment]
That's interesting.

Did you figure out what kind of device it was? Was it just a cheap mouse or was it something that actually might have a reason for breaking it that we could work around, such as maybe an very accurate joystick or something?

**Comment by shadiow6** [comment]
Yes it was a cheap wireless mouse and a controller, so I guess the problem was on my part.

**Comment by johan-bjareholt** [comment]
Alright, thank you!

**Comment by dogfuntom** [comment]
A wrote a workaround for those who are not ready to upgrade their mouses or controllers (or to unplug and replug them every 5 minutes): https://gist.github.com/dogfuntom/686e4ecf84f5b72eb4d700e98ce02227
