### ISSUE TITLE
All Electron based apps bundle up as "Electron"

### ISSUE THREAD

**Issue by ronilaukkarinen** [ActivityWatch/activitywatch#526]
- [X] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [X] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.15.7 Catalina
- **ActivityWatch version**: v0.10.0

## Describe the bug

When using for example Visual Studio Code, I expect to see "Visual Studio Code" in Applications and not "Electron".

## To Reproduce

    1. Use Visual Studio Code
    2. Go to main view
    3. See "Electron"

## Expected behavior

I expect to see app with its own name instead of the Electron framework.

**Comment by ErikBjare** [comment]
This is really an issue with Visual Studio Code, not ActivityWatch.

There's not much we can do to fix cases like this where an application doesn't provide an accurate app name (like https://github.com/ActivityWatch/aw-watcher-window/issues/31). But since the string 'Visual Studio Code' (or similar) probably shows up in the window title anyway, it's not that big of a deal.

**Comment by Programmierus** [comment]
Unfortunately I still see exactly same picture on latest AW running on latest Mac OS :( Very annoying since it bundles up many different apps and summarizing time from window titles (where it doesn't show "Visual Studio Code" but just workspace names) is a real hassle :(

**Comment by ErikBjare** [comment]
@iloveitaly seems to have solved this in https://github.com/ActivityWatch/aw-watcher-window/pull/52. 

Not sure why/how that approach differs from the old one, but it does.

**Comment by BelKed** [comment]
I had the same problem on macOS High Sierra, but after re-enabling the Accessibility permissions, it seems to work just fine...
However, the shown app name in ActivityWatch is just `Code`, not `Visual Studio Code`. This is because the app window on macOS is called `Code` (changing the app filename doesn't affect that).
