### ISSUE TITLE
macOS menubar icon is blurry

### ISSUE THREAD

**Issue by autonome** [ActivityWatch/activitywatch#529]
Are the source graphics available anywhere? I or someone else here can help make a higher resolution version.

**Comment by ErikBjare** [comment]
It isn't for me? Can we have a screenshot?

The source images are here: https://github.com/ActivityWatch/media

**Comment by autonome** [comment]
Big Sur, Fall 2020 Macbook Air (the new one w/ Apple chip)

<img width="194" alt="Screen Shot 2020-12-13 at 12 54 32 PM" src="https://user-images.githubusercontent.com/50103/102019580-62d20900-3d42-11eb-9aff-ef72dc3c92cd.png">

**Comment by ErikBjare** [comment]
Are you running a recent version?

This code specifies the icon to use: https://github.com/ActivityWatch/aw-qt/blob/d887ca573ea6b2dea00d31528e918da1bee9cc64/aw_qt/trayicon.py#L223-L226

Which is this image: https://github.com/ActivityWatch/media/blob/master/logo/black-monochrome-logo.png

It looks like plenty of resolution for an icon. Mine looks like this (on a low-ish VM with 1440p res viewed on a 4K host, not as clear difference as in your example):

![image](https://user-images.githubusercontent.com/1405370/102025928-3dbdb480-3d9b-11eb-99dd-56ccefd73a66.png)

It's possible the icon is downsampled or something before being used as the tray icon, but I don't think the issue is the source icon itself here.

Edit: I found this, which seems to indicate there's a flag we need to enable: https://forum.qt.io/post/561374. Weird that it doesn't "just work" though.

>Big Sur, Fall 2020 Macbook Air (the new one w/ Apple chip)

Wow, so I guess this means ActivityWatch runs fine on M1 with Rosetta? That's good news, didn't know :)

**Comment by russianryebread** [comment]
Just as a clarification, it's not just the icon which is blurry, the entire UI seems to be running at low resolution:

<img width="415" alt="Screen Shot 2021-02-16 at 10 21 18 AM" src="https://user-images.githubusercontent.com/747085/108091049-e9f07580-7040-11eb-8bd9-76d2d4b80b6e.png">

(I took the screenshot to show browser text underneath for comparison.)

**Comment by dumprop** [comment]
I, too, have it on big sur
<img width="173" alt="image" src="https://user-images.githubusercontent.com/34004367/108622998-59e17000-7434-11eb-9ed3-ed451ef42661.png">

**Comment by rakleed** [comment]
@ErikBjare, @johan-bjareholt I uninstalled ActivityWatch v0.10.0, rebooted macOS, installed [the most recent version](https://github.com/ActivityWatch/activitywatch/actions/runs/712157046), but I still have the icon and text in the menu blurred. Am I doing something wrong or is your fix not working?

<details>
<summary>Screenshot</summary>

<img width="186" alt="Снимок экрана 2021-04-22 в 00 35 40" src="https://user-images.githubusercontent.com/19418601/115624073-c678ce00-a302-11eb-9e74-06c20b4359f9.png">
</details>

**Comment by ErikBjare** [comment]
@rakleed The submodule had not been updated in the main repo, so was also not included in the nightly build. 

I've now updated the main repo, so if you try the latest build now that should include the fix.

**Comment by rakleed** [comment]
@ErikBjare Removed ActivityWatch, rebooted macOS, installed [the newest version](https://github.com/ActivityWatch/activitywatch/runs/2409727718) from the commit d396480, but the icon and text are still blurry. Why?

<details>
<summary>Screenshot</summary>

![Снимок экрана 2021-04-23 в 02 09 22](https://user-images.githubusercontent.com/19418601/115795667-00b49f00-a3d9-11eb-9252-058ef0abf67e.png)
</details>

**Comment by rakleed** [comment]
@ErikBjare on Windows in version 0.11.0 the icon is blurred as well.

**Comment by algoroq** [comment]
@ErikBjare on macOS Big Sur new version v0.11.0 the icon and menu is still blurred.
<img width="300" alt="Screenshot 2021-08-03 at 9 05 39" src="https://user-images.githubusercontent.com/1006087/127972721-247dd7b5-74e6-4066-8684-21a7b212ff9d.png">

**Comment by CharlesLiuyx** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/21956621/144393120-303d54f3-705f-4133-901f-213607e66211.png)

**Comment by michaeljelly** [comment]
It appear to me like this is an old version issue, having just built the latest from source. Mine is now crisp whereas before when I was using a packaged .dmg it was blurry. Don't know when the next packaged release will come out, but that may be what's needed to fix it.

![image](https://user-images.githubusercontent.com/53475252/146979180-2178bb1a-0014-434f-8846-92e31d6ed178.png)

**Comment by teunzwart** [comment]
As of June 2022, I am experiencing a blurry logo as well: ActivityWatch v0.11.0, macOS 12.4.0, MacBook Pro 16" 2021

**Comment by ErikBjare** [comment]
Locking this as the issue is fixed in v0.12.0b1 and beyond.

If anyone experiences this on v0.12.0b1 or later, open a new issue.
