### ISSUE TITLE
Multiple hosts with duplicated watchers

### ISSUE THREAD

**Issue by IIPatternII** [ActivityWatch/activitywatch#554]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS Catalina 10.15.7
- **ActivityWatch version**: 0.10.0

## Describe the bug

I have multiple hosts and duplicated activity watchers:

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/48034748/105642784-b881f100-5e6a-11eb-9776-bf0db25857c4.png">

I have seen issue #454 about merging multiple hosts and the [python script](https://github.com/ActivityWatch/aw-client/pull/50/commits/7c7747fa285faa153b21a60231887f9ede5bd771) to merge the buckets. I understand that the issue is caused by a change in the hostname, but in my case, I didn't change anything and I have multiple hosts and duplicated watchers from the very beginning. 

I would like to know if this is a problem because of a misconfiguration of my OS and if I merge the buckets and delete one of them, the extra host will reappear or not.

I'm happy to try the merge and report back, but I wanted to ask first because I don't know how this could affect my data.

Right now, some days the data is attributed to one host and other days to the other. I don't really know why.

## To Reproduce

    1. Install ActivityWatcher.
    2. Wait for a few days.

## Expected behavior

Just one host with one set of watchers attributed to that host.

**Comment by ErikBjare** [comment]
>I understand that the issue is caused by a change in the hostname, but in my case, I didn't change anything and I have multiple hosts and duplicated watchers from the very beginning.

You may not have changed your hostname yourself, but your hostname can be overridden automatically when you connect to a network (sometimes called the 'transient hostname'), which is probably what is happening in your case. 

It's an annoying bug for sure, and the plan is to resolve it by switching to using 'device IDs' instead of hostnames (see #302).

**Comment by drothmaler** [comment]
I have a similar issue... On my Mac the hostnames toggles between `BlaBla.local` and `BlaBla.fritz.box`... I found out, that the domain-part of the hostname changes when I (dis-)connect my VPN (wireguard). I looked for an alternative to a more stable alternative to `socket.gethostname()` but I couldn't find one (but I'm totally not a Python expert). It would be nice to have an option to tell ActivityWatch to ignore everything after the dot.

**Comment by BelKed** [comment]
I have the same problem. When ActivityWatch relaunches, the hostname simply switches from `{user}s-MBP` to `{user}s-MacBook-Pro.local`. It's really annoying because there are multiple buckets for same thing (e.g. multiple `window` buckets) and I have to manually merge them...
Now I've found that there is a [script](https://github.com/ActivityWatch/aw-client/blob/master/examples/merge_buckets.py) which really simplyfies that. Thank you @ErikBjare for creating it :)
