### ISSUE TITLE
Timeline: Please show the category

### ISSUE THREAD

**Issue by guettli** [ActivityWatch/activitywatch#573]
I created a regex to classify some window titles (via settings): .*(foo|bar|blu).*

But i am unsure if this regex does really match.

It would be very helpful if you show result of my custom regex in the timeline.

**Comment by johan-bjareholt** [comment]
Good point, categorization could be applied in the timeline too.

Another way to be able to know if a regex is matching today is to go to the Activity tab and use the "filter by category" dropdown, if your activity is shown when you have selected the category you wanted it to match with it will work.

**Comment by davidfraser** [comment]
This would be really useful to me. I just naturally expected it to work like this so I was editing categories, not realising that they don't display here. I use the timeline view more than any other view.
There is also a [forum request for this](https://forum.activitywatch.net/t/unified-category-colors-in-the-activity-and-timeline-view/2775)

I may want to work on the code - it looks like it would be about replacing the [usages of `getColorString`](https://github.com/search?q=repo%3AActivityWatch%2Faw-webui%20getColorFromString&type=code) with the other functions in [color.ts](https://github.com/ActivityWatch/aw-webui/blob/master/src/util/color.ts) like `getCategoryColorFromString` - possibly with making sure the right string is passed through there as it's not just the app title. Does that sound right?

This was closed as stale due to lack of activity; is it possible to reopen it? Or is it best to talk about this under #257 which mentioned it?

**Comment by ErikBjare** [comment]
Thanks David, would love to get your PR merged!

**Comment by ErikBjare** [comment]
Finally fixed by https://github.com/ActivityWatch/aw-webui/pull/609!
