### ISSUE TITLE
Label alignment in sunburst view

### ISSUE THREAD

**Issue by kulbhushanchand** [ActivityWatch/activitywatch#616]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

The labels on the sunburst diagram are overflowing and overlapping.

![image](https://user-images.githubusercontent.com/17742733/122673797-c2c4d300-d1ef-11eb-8cee-d588c90137cd.png)

It's not a bug, but maybe a design decision. 

**Possible changes: any of the following can be used**
- Labels can be better represented by following the arch of the sunburst component. 
- A legend for color codes can be used along with the sunburst. 
- The labels can be entirely removed and the category tree can be color-coded to serve as a legend for sunburst.

**Comment by ErikBjare** [comment]
Yeah the labels leave some things to be desired, but this is the best I got working without spending days on it (working with SVGs/D3.js can be difficult): https://github.com/David-Desmaisons/Vue.D3.sunburst/pull/15

Looks like @David-Desmaisons has been working on more improvements since, which will hopefully be in the next version.

If there are any D3.js ninjas around, I'd appreciate some PRs to the Vue.D3.sunburst repo!
