### ISSUE TITLE
Use computerid:5600 rather than localhost:5600

### ISSUE THREAD

**Issue by PeterKW** [ActivityWatch/activitywatch#647]
I was hoping to be able to open activitywatch from my computer host id rather than localhost. I believe I managed to do this before but I can't find the backup unfortunately. I imagine it's just tweaking some files but I haven't managed to figure it out. I thought I'd remembered changing the host value in the config last time I got this to work but perhaps there would be something else to do? I had a look through the documentation but I couldn't find anything on this at the moment. Thank you very much for any help.
 
/home/name/.config/activitywatch/aw-server/aw-server.ini
[server]
host = computerid
port = 5600
storage = peewee
cors_origins =

[server-testing]
host = computerid
port = 5666
storage = peewee
cors_origins =

**Comment by ErikBjare** [comment]
If `computerid` is really the hostname of your device, that alone should work. 

You could also set it to `0.0.0.0` to bind on all interfaces. 

Please keep in mind the usual security issues with doing this, since there's no API security you're exposing the server and all data to all other devices on your network.
