### ISSUE TITLE
Not each product is reflected in all comparison tables in the readme.

### ISSUE THREAD

**Issue by webbertakken** [ActivityWatch/activitywatch#686]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.

## Issue

Wakatime seems to be listed in all tables except [#platforms](https://github.com/ActivityWatch/activitywatch#platforms) in the readme. 

For the sake of transparency and not looking untrustworthy I would suggest to use the same products for all comparison tables.

**Comment by ErikBjare** [comment]
Maybe it's just me, but to me it doesn't really make sense to compare with Wakatime on platforms, since they don't really have any OS-specific code (just editor plugins).

Also, since the usecase doesn't really compare with the rest of the "general computer use tracking" group of software, which does require OS-specific code, and which is really the target group for the comparison table. Wakatime is only really in the table at all to highlight that it's an alternative to the specific editor-watching functionality. I don't see the point in listing which OS's it supports when it's not really dependent on your OS at all, but your editor. 

I assume prospective users can do their own research and find this out themselves, if they find Wakatime interesting, especially considering we link directly to the project.

Does this make sense? Or why do you think it looks untrustworthy as it is?

**Comment by webbertakken** [comment]
I'm just giving feedback from my experience, because that is the first thing I read in the ActivityWatch application.

So far this is the only thing that looked odd to me. And I thought it might help future users not be confused about the same thing.

Maybe we could add Wakatime in the platform table with N/A for the listed platform, to at least make explicit and give the context you provided above. If you feel it will not help anyone also feel free to close this issue.

**Comment by ErikBjare** [comment]
Your feedback is appreciated and noted. For now I think it stays as it is, but I'll keep it in mind for the future if I ever update the tables!

Thanks for the feedback! :)
