### ISSUE TITLE
Can't delete a view

### ISSUE THREAD

**Issue by sidharthpunathil** [ActivityWatch/activitywatch#706]
I am not able to delete a view created using the create view button.
![image](https://user-images.githubusercontent.com/31244727/150681385-9ba84b4b-28fe-4911-905f-965abfd15442.png)

Editing the name of the view will be nice. 

OS: Linux arch
Browser: Brave browser

**Comment by prplecake** [comment]
Here's a full bug report:




 - [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.




- **OS name and version**: macOS Monterey 12.3
- **ActivityWatch version**: v0.11.0 (also v0.11.0b1.dev+98fd120, which might just be the same version)

## Describe the bug
As stated above, inability to delete an additional view, however I'm only able to reproduce this if I leave the ID field of the New View form empty. Only the Name is actually required by validation. You'll also note that the URL doesn't show the view (should be something like `/activity/<hostname>/view/<view ID>`). 

## To Reproduce
1. Go to the ActivityWatch dashboard
2. Click "New view"
3. Give the view a name but **not** an ID.
4. Add a visualization.
5. Click "Edit view"
6. Try to delete view.

## Expected behavior
Don't allow a view to be created with a blank ID.

## Documentation
Note the URL yet the "test" view is active.
<img width="452" alt="Screen Shot 2022-02-19 at 22 13 04" src="https://user-images.githubusercontent.com/83595468/154828149-ac084f22-d1ec-4807-b369-31f7d12cc7c0.png">

I don't see anything relevant in the logs for aw-server. (I think I was running with `LOG_LEVEL=DEBUG`, but I didn't actually see any debug logs in the testing output.)

## Additional context
An ID should probably be required, or if it's left blank, we could slugify the name.

**Comment by ErikBjare** [comment]
This was fixed in https://github.com/ActivityWatch/aw-webui/pull/323
