### ISSUE TITLE
What is the proper way to change system time? / How does activity watch handle time conflicts?

### ISSUE THREAD

**Issue by KarlRW** [ActivityWatch/activitywatch#853]
- [x] I have searched the [issues](https://github.com/ActivityWatch/activitywatch/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.activitywatch.net/en/latest/) and believe that my question is not covered.
_(I had trouble finding info on this in the documentation.)_

## Question
I am on Windows 10. I need to change my system time back one hour. I am concerned that this will overwrite my previous hour of activity or cause some other issue. 

1. How will activity watch handle this (what will the timeline report look like for example)?
2. Is there a safe way to do this?

Thanks for the great work!

**Comment by ErikBjare** [comment]
Simply changing timezones should be a non-issue, since we always store UTC time.

However, if you change your system time for another reason, like trying to trick some other application, it's likely to lead to several short events being interspersed in the past, as the events fail to merge. There should be log messages warning about what is happening ("new" events being older than the most recent event). 

To be honest, I don't remember/am unsure what the behavior is in those cases. It's probably not good, and we should probably write tests for such scenarios, but it's likely to mess up things a tiny bit, but shouldn't be too bad. 

You could always backup your database file, restart ActivityWatch, change your system time, inspect the data, and optionally restore the old database file (see docs for where the database file is located).

**Comment by KarlRW** [comment]
Thanks for the quick response. It worked flawlessly. The timeline shifted back one hour and I saw no issues in the logs.


![activity_watch_before_and_after](https://user-images.githubusercontent.com/90365865/225397045-0a907c01-aed0-4959-bdf3-3d940d3bb90f.png)
